from __future__ import annotations

from typing import Any


def cross_market_operator_head_section_lines(
    *,
    status: str,
    brief: str,
    area: str,
    symbol: str,
    action: str,
    state: str,
    priority_score: str,
    priority_tier: str,
    backlog_count: str,
    backlog_brief: str,
    blocker_detail: str,
    done_when: str,
) -> list[str]:
    return [
        "## Cross-Market Operator Head Lane",
        f"- status=`{status or '-'}` brief=`{brief or '-'}`",
        f"- head=`{(area or '-') + ' | ' + (symbol or '-') + ' | ' + (action or '-') + ' | state=' + (state or '-') + ' | priority_score=' + (priority_score or '-') + ' | priority_tier=' + (priority_tier or '-')}`",
        f"- backlog=`{(backlog_count or '-') + ' | ' + (backlog_brief or '-')}`",
        f"- blocker=`{blocker_detail or '-'}`",
        f"- done_when=`{done_when or '-'}`",
        "",
    ]


def cross_market_operator_backlog_section_lines(
    *,
    source_status: str,
    source_as_of: str,
    source_artifact: str,
    snapshot_brief: str,
    backlog_status: str,
    backlog_count: str,
    backlog_state_brief: str,
    backlog_priority_totals_brief: str,
    lane_heads_brief: str,
    lane_priority_order_brief: str,
    backlog_brief: str,
    head_area: str,
    head_symbol: str,
    head_action: str,
    head_state: str,
    head_priority_score: str,
    head_priority_tier: str,
) -> list[str]:
    return [
        "## Cross-Market Operator Backlog",
        f"- source=`{(source_status or '-') + ' | ' + (source_as_of or '-') + ' | ' + (source_artifact or '-')}`",
        f"- snapshot=`{snapshot_brief or '-'}`",
        f"- backlog=`{(backlog_status or '-') + ' | count=' + (backlog_count or '-') + ' | states=' + (backlog_state_brief or '-') + ' | totals=' + (backlog_priority_totals_brief or '-') + ' | heads=' + (lane_heads_brief or '-') + ' | order=' + (lane_priority_order_brief or '-') + ' | ' + (backlog_brief or '-')}`",
        f"- head=`{(head_area or '-') + ' | ' + (head_symbol or '-') + ' | ' + (head_action or '-') + ' | state=' + (head_state or '-') + ' | priority_score=' + (head_priority_score or '-') + ' | priority_tier=' + (head_priority_tier or '-')}`",
        "",
    ]


def cross_market_remote_live_section_lines(
    *,
    gate_status: str,
    gate_brief: str,
    remote_snapshot_brief: str,
    gate_blocker_detail: str,
    gate_done_when: str,
    clearing_status: str,
    clearing_brief: str,
    clearing_blocker_detail: str,
    clearing_done_when: str,
) -> list[str]:
    return [
        "## Cross-Market Remote Live Takeover Gate",
        f"- status=`{gate_status or '-'}` brief=`{gate_brief or '-'}`",
        f"- snapshot=`{remote_snapshot_brief or '-'}`",
        f"- blocker=`{gate_blocker_detail or '-'}`",
        f"- done_when=`{gate_done_when or '-'}`",
        "",
        "## Cross-Market Remote Live Takeover Clearing",
        f"- status=`{clearing_status or '-'}` brief=`{clearing_brief or '-'}`",
        f"- blocker=`{clearing_blocker_detail or '-'}`",
        f"- done_when=`{clearing_done_when or '-'}`",
        "",
    ]


def cross_market_repair_section_lines(
    *,
    queue_status: str,
    queue_brief: str,
    queue_count: str,
    queue_head_area: str,
    queue_head_code: str,
    queue_head_action: str,
    queue_head_priority_score: str,
    queue_head_priority_tier: str,
    queue_head_command: str,
    queue_head_clear_when: str,
    queue_done_when: str,
    operator_repair_queue_count: str,
    operator_repair_queue_brief: str,
    operator_repair_checklist_brief: str,
    repair_head_status: str,
    repair_head_brief: str,
    repair_head_area: str,
    repair_head_code: str,
    repair_head_action: str,
    repair_head_priority_score: str,
    repair_head_priority_tier: str,
    repair_head_command: str,
    repair_head_clear_when: str,
    repair_backlog_status: str,
    repair_backlog_count: str,
    repair_backlog_priority_total: str,
    repair_backlog_brief: str,
    repair_head_done_when: str,
    repair_backlog_done_when: str,
) -> list[str]:
    return [
        "## Remote Live Takeover Repair Queue",
        f"- status=`{queue_status or '-'}` brief=`{queue_brief or '-'}` count=`{queue_count or '-'}`",
        f"- head=`{(queue_head_area or '-') + ' | ' + (queue_head_code or '-') + ' | ' + (queue_head_action or '-') + ' | priority=' + (queue_head_priority_score or '-') + '/' + (queue_head_priority_tier or '-')}`",
        f"- head_command=`{queue_head_command or '-'}`",
        f"- head_clear_when=`{queue_head_clear_when or '-'}`",
        f"- done_when=`{queue_done_when or '-'}`",
        "",
        "## Operator Repair Queue",
        f"- queue=`{(operator_repair_queue_count or '-') + ' | ' + (operator_repair_queue_brief or '-')}`",
        f"- checklist=`{operator_repair_checklist_brief or '-'}`",
        "",
        "## Cross-Market Operator Repair Head Lane",
        f"- status=`{repair_head_status or '-'}` brief=`{repair_head_brief or '-'}`",
        f"- head=`{(repair_head_area or '-') + ' | ' + (repair_head_code or '-') + ' | ' + (repair_head_action or '-') + ' | priority_score=' + (repair_head_priority_score or '-') + ' | priority_tier=' + (repair_head_priority_tier or '-')}`",
        f"- head_command=`{repair_head_command or '-'}`",
        f"- head_clear_when=`{repair_head_clear_when or '-'}`",
        f"- backlog=`{(repair_backlog_status or '-') + ' | count=' + (repair_backlog_count or '-') + ' | total=' + (repair_backlog_priority_total or '-') + ' | ' + (repair_backlog_brief or '-')}`",
        f"- done_when=`{repair_head_done_when or repair_backlog_done_when or '-'}`",
        "",
    ]


def cross_market_state_lanes_section_lines(
    *,
    waiting_status: str,
    waiting_count: str,
    waiting_priority_total: str,
    waiting_head_symbol: str,
    waiting_head_action: str,
    waiting_head_priority_score: str,
    waiting_head_priority_tier: str,
    waiting_brief: str,
    review_status: str,
    review_count: str,
    review_priority_total: str,
    review_head_symbol: str,
    review_head_action: str,
    review_head_priority_score: str,
    review_head_priority_tier: str,
    review_brief: str,
    watch_status: str,
    watch_count: str,
    watch_priority_total: str,
    watch_head_symbol: str,
    watch_head_action: str,
    watch_head_priority_score: str,
    watch_head_priority_tier: str,
    watch_brief: str,
    blocked_status: str,
    blocked_count: str,
    blocked_priority_total: str,
    blocked_head_symbol: str,
    blocked_head_action: str,
    blocked_head_priority_score: str,
    blocked_head_priority_tier: str,
    blocked_brief: str,
    repair_status: str,
    repair_count: str,
    repair_priority_total: str,
    repair_head_symbol: str,
    repair_head_action: str,
    repair_head_priority_score: str,
    repair_head_priority_tier: str,
    repair_brief: str,
) -> list[str]:
    return [
        "## Cross-Market Operator State Lanes",
        f"- waiting=`{(waiting_status or '-') + ' | count=' + (waiting_count or '-') + ' | total=' + (waiting_priority_total or '-') + ' | head=' + (waiting_head_symbol or '-') + ':' + (waiting_head_action or '-') + ':' + (waiting_head_priority_score or '-') + ':' + (waiting_head_priority_tier or '-') + ' | ' + (waiting_brief or '-')}`",
        f"- review=`{(review_status or '-') + ' | count=' + (review_count or '-') + ' | total=' + (review_priority_total or '-') + ' | head=' + (review_head_symbol or '-') + ':' + (review_head_action or '-') + ':' + (review_head_priority_score or '-') + ':' + (review_head_priority_tier or '-') + ' | ' + (review_brief or '-')}`",
        f"- watch=`{(watch_status or '-') + ' | count=' + (watch_count or '-') + ' | total=' + (watch_priority_total or '-') + ' | head=' + (watch_head_symbol or '-') + ':' + (watch_head_action or '-') + ':' + (watch_head_priority_score or '-') + ':' + (watch_head_priority_tier or '-') + ' | ' + (watch_brief or '-')}`",
        f"- blocked=`{(blocked_status or '-') + ' | count=' + (blocked_count or '-') + ' | total=' + (blocked_priority_total or '-') + ' | head=' + (blocked_head_symbol or '-') + ':' + (blocked_head_action or '-') + ':' + (blocked_head_priority_score or '-') + ':' + (blocked_head_priority_tier or '-') + ' | ' + (blocked_brief or '-')}`",
        f"- repair=`{(repair_status or '-') + ' | count=' + (repair_count or '-') + ' | total=' + (repair_priority_total or '-') + ' | head=' + (repair_head_symbol or '-') + ':' + (repair_head_action or '-') + ':' + (repair_head_priority_score or '-') + ':' + (repair_head_priority_tier or '-') + ' | ' + (repair_brief or '-')}`",
        "",
    ]


def cross_market_review_section_lines(
    *,
    review_head_status: str,
    review_head_brief: str,
    review_head_area: str,
    review_head_symbol: str,
    review_head_action: str,
    review_head_priority_score: str,
    review_head_priority_tier: str,
    review_backlog_count: str,
    review_backlog_brief: str,
    review_head_blocker_detail: str,
    review_head_done_when: str,
    source_status: str,
    source_as_of: str,
    source_artifact: str,
    review_snapshot_brief: str,
    source_backlog_status: str,
    source_backlog_count: str,
    source_backlog_brief: str,
    source_head_area: str,
    source_head_symbol: str,
    source_head_action: str,
    source_head_priority_score: str,
    source_head_priority_tier: str,
) -> list[str]:
    return [
        "## Cross-Market Review Head Lane",
        f"- status=`{review_head_status or '-'}` brief=`{review_head_brief or '-'}`",
        f"- head=`{(review_head_area or '-') + ' | ' + (review_head_symbol or '-') + ' | ' + (review_head_action or '-') + ' | priority_score=' + (review_head_priority_score or '-') + ' | priority_tier=' + (review_head_priority_tier or '-')}`",
        f"- backlog=`{(review_backlog_count or '-') + ' | ' + (review_backlog_brief or '-')}`",
        f"- blocker=`{review_head_blocker_detail or '-'}`",
        f"- done_when=`{review_head_done_when or '-'}`",
        "",
        "## Cross-Market Review Backlog",
        f"- source=`{(source_status or '-') + ' | ' + (source_as_of or '-') + ' | ' + (source_artifact or '-')}`",
        f"- snapshot=`{review_snapshot_brief or '-'}`",
        f"- backlog=`{(source_backlog_status or '-') + ' | count=' + (source_backlog_count or '-') + ' | ' + (source_backlog_brief or '-')}`",
        f"- head=`{(source_head_area or '-') + ' | ' + (source_head_symbol or '-') + ' | ' + (source_head_action or '-') + ' | priority_score=' + (source_head_priority_score or '-') + ' | priority_tier=' + (source_head_priority_tier or '-')}`",
        "",
    ]


def system_time_sync_repair_plan_section_lines(
    *,
    status: str,
    brief: str,
    artifact: str,
    admin_required: Any,
    done_when: str,
) -> list[str]:
    return [
        "## System Time Sync Repair Plan",
        f"- status=`{status or '-'}` brief=`{brief or '-'}`",
        f"- artifact=`{artifact or '-'}`",
        f"- admin_required=`{admin_required}`",
        f"- done_when=`{done_when or '-'}`",
        "",
    ]


def system_time_sync_repair_verification_section_lines(
    *,
    status: str,
    brief: str,
    artifact: str,
    cleared: Any,
) -> list[str]:
    return [
        "## System Time Sync Repair Verification",
        f"- status=`{status or '-'}` brief=`{brief or '-'}`",
        f"- artifact=`{artifact or '-'}`",
        f"- cleared=`{cleared}`",
        "",
    ]


def openclaw_orderflow_blueprint_section_lines(
    *,
    status: str,
    brief: str,
    artifact: str,
    current_life_stage: str,
    target_life_stage: str,
    intent_queue_brief: str,
    intent_queue_recommendation: str,
    execution_journal_brief: str,
    orderflow_feedback_brief: str,
    orderflow_policy_brief: str,
    execution_ack_brief: str,
    canary_gate_brief: str,
    quality_report_brief: str,
    guardian_clearance_brief: str = "",
    guardian_clearance_top: str = "",
    live_boundary_hold_brief: str = "",
    promotion_gate_brief: str = "",
    promotion_gate_top: str = "",
    shadow_learning_continuity_brief: str = "",
    promotion_unblock_readiness_brief: str = "",
    ticket_actionability_brief: str = "",
    shortline_backtest_slice_brief: str = "",
    shortline_cross_section_backtest_brief: str = "",
    time_sync_mode: str = "",
    shadow_clock_evidence_brief: str = "",
    backlog_top: str,
) -> list[str]:
    return [
        "## OpenClaw Orderflow Blueprint",
        f"- status=`{status or '-'}` brief=`{brief or '-'}`",
        f"- artifact=`{artifact or '-'}`",
        f"- life_stage=`{current_life_stage or '-'} -> {target_life_stage or '-'}`",
        f"- intent_queue=`{intent_queue_brief or '-'}`",
        f"- intent_recommendation=`{intent_queue_recommendation or '-'}`",
        f"- execution_journal=`{execution_journal_brief or '-'}`",
        f"- orderflow_feedback=`{orderflow_feedback_brief or '-'}`",
        f"- orderflow_policy=`{orderflow_policy_brief or '-'}`",
        f"- execution_ack=`{execution_ack_brief or '-'}`",
        f"- canary_gate=`{canary_gate_brief or '-'}`",
        f"- quality_report=`{quality_report_brief or '-'}`",
        f"- guardian_clearance=`{guardian_clearance_brief or '-'}`",
        f"- guardian_clearance_top=`{guardian_clearance_top or '-'}`",
        f"- live_boundary_hold=`{live_boundary_hold_brief or '-'}`",
        f"- promotion_gate=`{promotion_gate_brief or '-'}`",
        f"- promotion_gate_top=`{promotion_gate_top or '-'}`",
        f"- shadow_learning_continuity=`{shadow_learning_continuity_brief or '-'}`",
        f"- promotion_unblock_readiness=`{promotion_unblock_readiness_brief or '-'}`",
        f"- ticket_actionability=`{ticket_actionability_brief or '-'}`",
        f"- shortline_backtest_slice=`{shortline_backtest_slice_brief or '-'}`",
        f"- shortline_cross_section_backtest=`{shortline_cross_section_backtest_brief or '-'}`",
        f"- time_sync_mode=`{time_sync_mode or '-'}`",
        f"- shadow_clock_evidence=`{shadow_clock_evidence_brief or '-'}`",
        f"- backlog_top=`{backlog_top or '-'}`",
        "",
    ]


def remote_live_account_scope_section_lines(
    *,
    status: str,
    as_of: str,
    state: str,
    artifact: str,
    snapshot: str,
    ready_scope_brief: str,
    ready_scope_market: str,
    alignment_brief: str,
    alignment_blocking: Any,
    alignment_blocker_detail: str,
) -> list[str]:
    return [
        "## Remote Live Account Scope",
        f"- status=`{status or '-'}` as_of=`{as_of or '-'}` state=`{state or '-'}` path=`{artifact or '-'}`",
        f"- snapshot=`{snapshot or '-'}`",
        f"- ready_scope=`{ready_scope_brief or '-'}` market=`{ready_scope_market or '-'}`",
        f"- alignment=`{alignment_brief or '-'} | blocking={alignment_blocking}`",
        f"- alignment_blocker=`{alignment_blocker_detail or '-'}`",
        "",
    ]
